name: Buildroot Test

on:
  push:
    tags:
      - 'assignment-4-part-1*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set BR2_EXTERNAL
      run: echo "BR2_EXTERNAL=${{ github.workspace }}/base_external" >> $GITHUB_ENV

    - name: Build Buildroot
      run: |
        cd ${{ github.workspace }}/buildroot
        make aesd_defconfig
        make

    - name: Run tests
      run: |
        cd ${{ github.workspace }}/assignment-autotest
        ./run-tests.sh
