name: Assignment 4 Part 1

on:
  push:
    branches: [ "main" ]

jobs:
  buildroot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Debug paths
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "Directory listing:"
          ls -R $GITHUB_WORKSPACE

      - name: Build Buildroot
        run: |
          cd $GITHUB_WORKSPACE/buildroot
          echo "Using BR2_EXTERNAL=$GITHUB_WORKSPACE/base_external"
          make BR2_EXTERNAL=$GITHUB_WORKSPACE/base_external aesd_defconfig
          make BR2_EXTERNAL=$GITHUB_WORKSPACE/base_external
